# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gui}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = %q{2010-11-18}
  s.description = %q{audioboo gui}
  s.email = %q{you@email.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/gui/widgets_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/gui/widgets_helper.rb",
    "app/models/gui/widget.rb",
    "app/views/gui/widgets/index.html.erb",
    "app/views/gui/widgets/show.html.erb",
    "app/views/layouts/gui.html.erb",
    "config/routes.rb",
    "lib/acts_as_widget/base.rb",
    "lib/application_helper.rb",
    "lib/engine.rb",
    "lib/gui.rb"
  ]
  s.homepage = %q{}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{hoo gui engine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

